### ISSUE TITLE
Dropdown not working on live link while searching for repository

### ISSUE THREAD

**Issue by sagaragarwal94** [sagaragarwal94/github-search#3]
On searching org, it is showing the results. The issue is the dropdown not getting displayed 👎

**Comment by sagaragarwal94** [comment]
Tags are working when manual link is changed 👍

**Comment by hiteshgarg14** [comment]
changing  requests to the CDN from http to https:

**Comment by sagaragarwal94** [comment]
Solved with commit`https://github.com/sagaragarwal94/github-search/commit/fc45b7af7e65e033651d6ed7805e365dd6a0c97e`.
